{% set name = "starfile" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starfile-{{ version }}.tar.gz
  sha256: f65ad12bad6b64b40bd101bf0aeb4c6ed2342e8f6e10473ac68a3dfe7a236ed4

build:
  entry_points:
    - starfile = starfile.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - starfile
  commands:
    - pip list
    - pip check
    - starfile --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/starfile
  summary: STAR file reading and writing in python.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/alisterburt/starfile

extra:
  recipe-maintainers:
    - alisterburt
    - goanpeca
